# Generated by Django 5.0.7 on 2024-07-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basemodal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('soft_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther_name', models.CharField(db_index=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('image', models.FileField(db_index=True, null=True, upload_to='Blog_image')),
                ('title', models.CharField(db_index=True, max_length=100, null=True)),
                ('description', models.CharField(db_index=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, null=True)),
                ('description', models.CharField(db_index=True, max_length=100, null=True)),
                ('image', models.FileField(db_index=True, null=True, upload_to='Service_image')),
                ('status', models.BooleanField()),
            ],
        ),
    ]
