# Generated by Django 5.0.7 on 2024-08-08 07:29

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_blog_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basemodal',
        ),
        migrations.AlterModelManagers(
            name='blog',
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
