# Generated by Django 5.0.7 on 2024-08-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_service_managers_service_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
